import { StyleSheet, Dimensions } from 'react-native';
//
export const ImageUrl = {
	i_iconHome: require('../Images/Icon/home0.png'),
	i_iconCart: require('../Images/Icon/cart0.png'),
	i_iconCartGreen: require('../Images/Icon/cartfull.png'),
	i_iconSearch: require('../Images/Icon/search0.png'),
	i_iconContact: require('../Images/Icon/contact0.png'),
	i_iconMenu: require('../Images/Icon/ic_menu.png'),
	i_iconLogo: require('../Images/Icon/ic_logo.png'),
	i_banner: require('../Images/Layout/banner.jpg'),
	i_category1: require('../Images/Layout/fit.jpg'),
	i_category2: require('../Images/Layout/little.jpg'),
	i_category3: require('../Images/Layout/maxi.jpg'),
	i_category4: require('../Images/Layout/midi.jpg'),
	i_topProduct1: require('../Images/Layout/sp1.jpeg'),
	i_topProduct2: require('../Images/Layout/sp2.jpeg'),
	i_topProduct3: require('../Images/Layout/sp3.jpeg'),
	i_topProduct4: require('../Images/Layout/sp4.jpeg'),
	i_topProduct5: require('../Images/Layout/sp5.jpeg'),
	i_avatar: require('../Images/Layout/profile.png'),
	i_back: require('../Images/Icon/back_white.png'),
	i_backRight: require('../Images/Icon/backs.png'),
	i_backList: require('../Images/Icon/backList.png'),
	i_backProduct: require('../Images/Icon/back.png'),
	i_iconPhone: require('../Images/Icon/phone.png'),
	i_iconMail: require('../Images/Icon/mail.png'),
	i_iconMessage: require('../Images/Icon/message.png'),
	i_iconLocation: require('../Images/Icon/location.png'),
}