export const Language = {
	l_home: 'Home',
	l_cart: 'Cart',
	l_search: 'Search',
	l_contact: 'Contact',
	l_titleApp: 'Wearing a Dress',
	l_titleSearch: 'What do you want to buy?',
	l_collection: 'Spring Collection',
	l_category: 'List of Category',
	l_topProduct: 'Top Product',
	l_orderHistory: 'Order History',
	l_changeInfo: 'Change Infomation',
	l_signOut: 'Sign Out',
	l_signIn: 'Sign In',
	l_signInNow: 'Sign In Now',
	l_email: 'Enter your email',
	l_password: 'Enter your password',
	l_signUp: 'Sign Up',
	l_signUpNow: 'Sign Up Now',
	l_name: 'Enter your name',
	l_rePassword: 'Re-enter your password',
	l_point: '.',
	l_orderId: 'Order Id:',
	l_orderTime: 'Order Time:',
	l_orderStatus: 'Status:',
	l_orderTotal: 'Total:',
	l_userInfos: 'User Infomation',
	l_btnUserInfos: 'Change Your Infomation',
	l_showDetail: 'Show details',
	l_totalCart: 'Total',
	l_checkOutNow: 'Checkout Now',
	l_unitCurrency: '$',
}